for n in range(5):
    substantivo_singular = input('Informe um substantivo no singular: ')
    substantivo_plural = input('Informe um substantivo no plural: ')
    adjetivo = input('Informe um adjetivo: ')
    lugar = input('Informe um lugar: ')
    verbo = input('Informe um verbo (ex: voar): ')
    print(f'Era uma vez um(a) {substantivo_singular} que gostava de {verbo}')
    print('mas sempre que o fazia, começavam a reclamar,')
    print(f'suas {substantivo_plural} o ajudavam a continuar')
    print(f'porém sempre que o(a) {substantivo_singular} ficava {adjetivo}')
    print(f'ele ia para {lugar} chorar.')
    print(f'Mesmo com todos criticando ele não desistia de {verbo}.')