n1 = float(input('Digite a primeira nota: '))
n2 = float(input('Digite a segunda nota: '))
n3 = float(input('Digite a terceira nota: '))
n4 = float(input('Digite a quarta nota: '))
print('A média entre as 4 notas foi de: {}'.format((n1 + n2 + n3 + n4)/4))